rules:
  paths-kebab-case:
    description: Paths should start with your projects assigned prefix.
    message: "{{property}} should be kebab-case (lower-case and separated with hyphens)"
    severity: warn
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/|anything1"
