rules:
  paths-start-with-projects-pathname:
    description: Paths should start with your projects assigned prefix.
    message: "{{property}} should contain project approved prefix"
    severity: warn
    given: 
      - $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/project1)"